### ISSUE TITLE
ivi shell to support multiple display

### ISSUE THREAD

**Issue by mbinoy** [ntanibata/weston-ivi-shell#9]
Hello everyone,

Kindly provide some help on below,

Does ivi-shell supports multiple display? or what version of weston and configuration should i use to support second display using ivi shell

I am using weston 1.9 and ivi shell, and tried to drive multiple displays connected through two hdmi ports in our rareness board. 

using default weston shell i am able to see the second display in extended mode, but not able to setup the second display in ivi shell

the weston.ini looks similar to below.

[output]
name=HDMI-A-1
mode=1920x720

[output]
name=HDMI-A-2
# mode=preferred

mode=1024x768

[core]
shell=ivi-shell.so

[ivi-shell]
ivi-module=hmi-controller.so
ivi-shell-user-interface=/usr/lib64/weston/weston-ivi-shell-user-interface

base-layer-id=1000
workspace-background-layer-id=2000
workspace-layer-id=3000
application-layer-id=4000

transition-duration=300

background-image=/usr/share/weston/background.png
background-id=1001
panel-image=/usr/share/weston/panel.png
panel-id=1002
tiling-image=/usr/share/weston/tiling.png
tiling-id=1003
sidebyside-image=/usr/share/weston/sidebyside.png
sidebyside-id=1004
fullscreen-image=/usr/share/weston/fullscreen.png
fullscreen-id=1005
random-image=/usr/share/weston/random.png
random-id=1006
home-image=/usr/share/weston/home.png
home-id=1007
workspace-background-color=0x99000000
workspace-background-id=2001

[input-method]
path=/usr/lib64/weston/weston-keyboard

[ivi-launcher]
workspace-id=0
icon-id=4001
icon=/usr/share/weston/icon_ivi_flower.png
path=/usr/bin/weston-flower

[ivi-launcher]
workspace-id=0
icon-id=4002
icon=/usr/share/weston/icon_ivi_clickdot.png
path=/usr/bin/weston-clickdot

[ivi-launcher]
workspace-id=1
icon-id=4003
icon=/usr/share/weston/icon_ivi_simple-egl.png
path=/usr/bin/weston-simple-egl

[ivi-launcher]
workspace-id=1
icon-id=4004
icon=/usr/share/weston/icon_ivi_simple-shm.png
path=/uhm

[ivi-launcher]
workspace-id=3
icon-id=4010
icon=/usr/share/weston/icon_ivi_smoke.png
path=/usr/bin/weston-smoke

**Comment by SrinuRepo** [comment]
Can anyone provide solution to above question please?
